/**
 * Think About IT BC
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ThinkAboutItBc);
  }
}(this, function(expect, ThinkAboutItBc) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ThinkAboutItBc.Comment();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Comment', function() {
    it('should create an instance of Comment', function() {
      // uncomment below and update the code to test Comment
      //var instane = new ThinkAboutItBc.Comment();
      //expect(instance).to.be.a(ThinkAboutItBc.Comment);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new ThinkAboutItBc.Comment();
      //expect(instance).to.be();
    });

    it('should have the property agree (base name: "agree")', function() {
      // uncomment below and update the code to test the property agree
      //var instane = new ThinkAboutItBc.Comment();
      //expect(instance).to.be();
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instane = new ThinkAboutItBc.Comment();
      //expect(instance).to.be();
    });

    it('should have the property text (base name: "text")', function() {
      // uncomment below and update the code to test the property text
      //var instane = new ThinkAboutItBc.Comment();
      //expect(instance).to.be();
    });

    it('should have the property image (base name: "image")', function() {
      // uncomment below and update the code to test the property image
      //var instane = new ThinkAboutItBc.Comment();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "createdAt")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instane = new ThinkAboutItBc.Comment();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updatedAt")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instane = new ThinkAboutItBc.Comment();
      //expect(instance).to.be();
    });

    it('should have the property createdBy (base name: "createdBy")', function() {
      // uncomment below and update the code to test the property createdBy
      //var instane = new ThinkAboutItBc.Comment();
      //expect(instance).to.be();
    });

    it('should have the property post (base name: "post")', function() {
      // uncomment below and update the code to test the property post
      //var instane = new ThinkAboutItBc.Comment();
      //expect(instance).to.be();
    });

  });

}));
