/**
 * Think About IT BC
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ThinkAboutItBc);
  }
}(this, function(expect, ThinkAboutItBc) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ThinkAboutItBc.AccountApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AccountApi', function() {
    describe('accountAccessDeniedGet', function() {
      it('should call accountAccessDeniedGet successfully', function(done) {
        //uncomment below and update the code to test accountAccessDeniedGet
        //instance.accountAccessDeniedGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('accountConfirmEmailGet', function() {
      it('should call accountConfirmEmailGet successfully', function(done) {
        //uncomment below and update the code to test accountConfirmEmailGet
        //instance.accountConfirmEmailGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('accountExternalLoginCallbackGet', function() {
      it('should call accountExternalLoginCallbackGet successfully', function(done) {
        //uncomment below and update the code to test accountExternalLoginCallbackGet
        //instance.accountExternalLoginCallbackGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('accountExternalLoginConfirmationPost', function() {
      it('should call accountExternalLoginConfirmationPost successfully', function(done) {
        //uncomment below and update the code to test accountExternalLoginConfirmationPost
        //instance.accountExternalLoginConfirmationPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('accountExternalLoginPost', function() {
      it('should call accountExternalLoginPost successfully', function(done) {
        //uncomment below and update the code to test accountExternalLoginPost
        //instance.accountExternalLoginPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('accountForgotPasswordConfirmationGet', function() {
      it('should call accountForgotPasswordConfirmationGet successfully', function(done) {
        //uncomment below and update the code to test accountForgotPasswordConfirmationGet
        //instance.accountForgotPasswordConfirmationGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('accountForgotPasswordGet', function() {
      it('should call accountForgotPasswordGet successfully', function(done) {
        //uncomment below and update the code to test accountForgotPasswordGet
        //instance.accountForgotPasswordGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('accountForgotPasswordPost', function() {
      it('should call accountForgotPasswordPost successfully', function(done) {
        //uncomment below and update the code to test accountForgotPasswordPost
        //instance.accountForgotPasswordPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('accountLockoutGet', function() {
      it('should call accountLockoutGet successfully', function(done) {
        //uncomment below and update the code to test accountLockoutGet
        //instance.accountLockoutGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('accountLoginGet', function() {
      it('should call accountLoginGet successfully', function(done) {
        //uncomment below and update the code to test accountLoginGet
        //instance.accountLoginGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('accountLoginPost', function() {
      it('should call accountLoginPost successfully', function(done) {
        //uncomment below and update the code to test accountLoginPost
        //instance.accountLoginPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('accountLoginWith2faGet', function() {
      it('should call accountLoginWith2faGet successfully', function(done) {
        //uncomment below and update the code to test accountLoginWith2faGet
        //instance.accountLoginWith2faGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('accountLoginWith2faPost', function() {
      it('should call accountLoginWith2faPost successfully', function(done) {
        //uncomment below and update the code to test accountLoginWith2faPost
        //instance.accountLoginWith2faPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('accountLoginWithRecoveryCodeGet', function() {
      it('should call accountLoginWithRecoveryCodeGet successfully', function(done) {
        //uncomment below and update the code to test accountLoginWithRecoveryCodeGet
        //instance.accountLoginWithRecoveryCodeGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('accountLoginWithRecoveryCodePost', function() {
      it('should call accountLoginWithRecoveryCodePost successfully', function(done) {
        //uncomment below and update the code to test accountLoginWithRecoveryCodePost
        //instance.accountLoginWithRecoveryCodePost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('accountLogoutPost', function() {
      it('should call accountLogoutPost successfully', function(done) {
        //uncomment below and update the code to test accountLogoutPost
        //instance.accountLogoutPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('accountRegisterGet', function() {
      it('should call accountRegisterGet successfully', function(done) {
        //uncomment below and update the code to test accountRegisterGet
        //instance.accountRegisterGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('accountRegisterPost', function() {
      it('should call accountRegisterPost successfully', function(done) {
        //uncomment below and update the code to test accountRegisterPost
        //instance.accountRegisterPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('accountResetPasswordConfirmationGet', function() {
      it('should call accountResetPasswordConfirmationGet successfully', function(done) {
        //uncomment below and update the code to test accountResetPasswordConfirmationGet
        //instance.accountResetPasswordConfirmationGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('accountResetPasswordGet', function() {
      it('should call accountResetPasswordGet successfully', function(done) {
        //uncomment below and update the code to test accountResetPasswordGet
        //instance.accountResetPasswordGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('accountResetPasswordPost', function() {
      it('should call accountResetPasswordPost successfully', function(done) {
        //uncomment below and update the code to test accountResetPasswordPost
        //instance.accountResetPasswordPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiRegisterPost', function() {
      it('should call apiRegisterPost successfully', function(done) {
        //uncomment below and update the code to test apiRegisterPost
        //instance.apiRegisterPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
