/**
 * Think About IT BC
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ThinkAboutItBc);
  }
}(this, function(expect, ThinkAboutItBc) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ThinkAboutItBc.ManageApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ManageApi', function() {
    describe('manageChangePasswordGet', function() {
      it('should call manageChangePasswordGet successfully', function(done) {
        //uncomment below and update the code to test manageChangePasswordGet
        //instance.manageChangePasswordGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('manageChangePasswordPost', function() {
      it('should call manageChangePasswordPost successfully', function(done) {
        //uncomment below and update the code to test manageChangePasswordPost
        //instance.manageChangePasswordPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('manageDisable2faPost', function() {
      it('should call manageDisable2faPost successfully', function(done) {
        //uncomment below and update the code to test manageDisable2faPost
        //instance.manageDisable2faPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('manageDisable2faWarningGet', function() {
      it('should call manageDisable2faWarningGet successfully', function(done) {
        //uncomment below and update the code to test manageDisable2faWarningGet
        //instance.manageDisable2faWarningGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('manageEnableAuthenticatorGet', function() {
      it('should call manageEnableAuthenticatorGet successfully', function(done) {
        //uncomment below and update the code to test manageEnableAuthenticatorGet
        //instance.manageEnableAuthenticatorGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('manageEnableAuthenticatorPost', function() {
      it('should call manageEnableAuthenticatorPost successfully', function(done) {
        //uncomment below and update the code to test manageEnableAuthenticatorPost
        //instance.manageEnableAuthenticatorPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('manageExternalLoginsGet', function() {
      it('should call manageExternalLoginsGet successfully', function(done) {
        //uncomment below and update the code to test manageExternalLoginsGet
        //instance.manageExternalLoginsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('manageGenerateRecoveryCodesGet', function() {
      it('should call manageGenerateRecoveryCodesGet successfully', function(done) {
        //uncomment below and update the code to test manageGenerateRecoveryCodesGet
        //instance.manageGenerateRecoveryCodesGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('manageIndexGet', function() {
      it('should call manageIndexGet successfully', function(done) {
        //uncomment below and update the code to test manageIndexGet
        //instance.manageIndexGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('manageIndexPost', function() {
      it('should call manageIndexPost successfully', function(done) {
        //uncomment below and update the code to test manageIndexPost
        //instance.manageIndexPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('manageLinkLoginCallbackGet', function() {
      it('should call manageLinkLoginCallbackGet successfully', function(done) {
        //uncomment below and update the code to test manageLinkLoginCallbackGet
        //instance.manageLinkLoginCallbackGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('manageLinkLoginPost', function() {
      it('should call manageLinkLoginPost successfully', function(done) {
        //uncomment below and update the code to test manageLinkLoginPost
        //instance.manageLinkLoginPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('manageRemoveLoginPost', function() {
      it('should call manageRemoveLoginPost successfully', function(done) {
        //uncomment below and update the code to test manageRemoveLoginPost
        //instance.manageRemoveLoginPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('manageResetAuthenticatorPost', function() {
      it('should call manageResetAuthenticatorPost successfully', function(done) {
        //uncomment below and update the code to test manageResetAuthenticatorPost
        //instance.manageResetAuthenticatorPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('manageResetAuthenticatorWarningGet', function() {
      it('should call manageResetAuthenticatorWarningGet successfully', function(done) {
        //uncomment below and update the code to test manageResetAuthenticatorWarningGet
        //instance.manageResetAuthenticatorWarningGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('manageSendVerificationEmailPost', function() {
      it('should call manageSendVerificationEmailPost successfully', function(done) {
        //uncomment below and update the code to test manageSendVerificationEmailPost
        //instance.manageSendVerificationEmailPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('manageSetPasswordGet', function() {
      it('should call manageSetPasswordGet successfully', function(done) {
        //uncomment below and update the code to test manageSetPasswordGet
        //instance.manageSetPasswordGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('manageSetPasswordPost', function() {
      it('should call manageSetPasswordPost successfully', function(done) {
        //uncomment below and update the code to test manageSetPasswordPost
        //instance.manageSetPasswordPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('manageTwoFactorAuthenticationGet', function() {
      it('should call manageTwoFactorAuthenticationGet successfully', function(done) {
        //uncomment below and update the code to test manageTwoFactorAuthenticationGet
        //instance.manageTwoFactorAuthenticationGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
